USE [master]
GO

/****** Object:  Database [BD_GUARANGOS]    Script Date: 31/01/2024 19:12:25 ******/
CREATE DATABASE [BD_GUARANGOS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD_GUARANGOS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLSERVER2016\MSSQL\DATA\BD_GUARANGOS.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BD_GUARANGOS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLSERVER2016\MSSQL\DATA\BD_GUARANGOS_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_GUARANGOS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BD_GUARANGOS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BD_GUARANGOS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BD_GUARANGOS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BD_GUARANGOS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BD_GUARANGOS] SET ARITHABORT OFF 
GO

ALTER DATABASE [BD_GUARANGOS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BD_GUARANGOS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BD_GUARANGOS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BD_GUARANGOS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BD_GUARANGOS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BD_GUARANGOS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BD_GUARANGOS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BD_GUARANGOS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BD_GUARANGOS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BD_GUARANGOS] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BD_GUARANGOS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BD_GUARANGOS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BD_GUARANGOS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BD_GUARANGOS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BD_GUARANGOS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BD_GUARANGOS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BD_GUARANGOS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BD_GUARANGOS] SET RECOVERY FULL 
GO

ALTER DATABASE [BD_GUARANGOS] SET  MULTI_USER 
GO

ALTER DATABASE [BD_GUARANGOS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BD_GUARANGOS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BD_GUARANGOS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BD_GUARANGOS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BD_GUARANGOS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BD_GUARANGOS] SET QUERY_STORE = OFF
GO

USE [BD_GUARANGOS]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [BD_GUARANGOS] SET  READ_WRITE 
GO

